// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
// SCREEN: ui_loadingScreen
void ui_loadingScreen_screen_init(void);
extern lv_obj_t *ui_loadingScreen;
extern lv_obj_t *ui_Label1;
void ui_event_Panel3( lv_event_t * e);
extern lv_obj_t *ui_Panel3;
extern lv_obj_t *ui_Label8;
void ui_event_Panel4( lv_event_t * e);
extern lv_obj_t *ui_Panel4;
void ui_event_Label9( lv_event_t * e);
extern lv_obj_t *ui_Label9;
void ui_event_Panel5( lv_event_t * e);
extern lv_obj_t *ui_Panel5;
void ui_event_Label13( lv_event_t * e);
extern lv_obj_t *ui_Label13;
// SCREEN: ui_newOrExistingConnections
void ui_newOrExistingConnections_screen_init(void);
extern lv_obj_t *ui_newOrExistingConnections;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_newConnectionCB;
extern lv_obj_t *ui_existConnectionCB;
void ui_event_NewExistingCancelBtn( lv_event_t * e);
extern lv_obj_t *ui_NewExistingCancelBtn;
extern lv_obj_t *ui_ExistingCancelL;
void ui_event_NewExistingOkBtn( lv_event_t * e);
extern lv_obj_t *ui_NewExistingOkBtn;
extern lv_obj_t *ui_ExistingOkL;
// SCREEN: ui_chooseConnection
void ui_chooseConnection_screen_init(void);
extern lv_obj_t *ui_chooseConnection;
extern lv_obj_t *ui_ssidPanel;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_Label6;
void ui_event_chooseConnectionOKBtn_StandardButton( lv_event_t * e);
extern lv_obj_t *ui_chooseConnectionOKBtn;
void ui_event_StandardButton3_StandardButton( lv_event_t * e);
extern lv_obj_t *ui_StandardButton3;
extern lv_obj_t *ui_StandardButton4;
// SCREEN: ui_passphrase
void ui_passphrase_screen_init(void);
extern lv_obj_t *ui_passphrase;
extern lv_obj_t *ui_Label10;
extern lv_obj_t *ui_passphraseText;
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_Keyboard1;
void ui_event_passphraseOKBtn_StandardButton( lv_event_t * e);
extern lv_obj_t *ui_passphraseOKBtn;
void ui_event_StandardButton1_StandardButton( lv_event_t * e);
extern lv_obj_t *ui_StandardButton1;
// SCREEN: ui_setTimeScreen
void ui_setTimeScreen_screen_init(void);
void ui_event_setTimeScreen( lv_event_t * e);
extern lv_obj_t *ui_setTimeScreen;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_internetTime;
void ui_event_TimeDateDoneBtn_StandardButton( lv_event_t * e);
extern lv_obj_t *ui_TimeDateDoneBtn;
extern lv_obj_t *ui_twentyFourHrMode;
extern lv_obj_t *ui_Dropdown1;
extern lv_obj_t *ui_Label11;
// SCREEN: ui_TimeScreen
void ui_TimeScreen_screen_init(void);
void ui_event_TimeScreen( lv_event_t * e);
extern lv_obj_t *ui_TimeScreen;
extern lv_obj_t *ui_TimeSreenSkipButton;
extern lv_obj_t *ui_TimeScreenDarkButton;
extern lv_obj_t *ui_TimeScreenTimeLabel;
extern lv_obj_t *ui____initial_actions0;




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
