// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_COMP_STANDARDBUTTON_H
#define _UI_COMP_STANDARDBUTTON_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT StandardButton
#define UI_COMP_STANDARDBUTTON_STANDARDBUTTON 0
#define UI_COMP_STANDARDBUTTON_LABEL12 1
#define _UI_COMP_STANDARDBUTTON_NUM 2
lv_obj_t *ui_StandardButton_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
