// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_newOrExistingConnections_screen_init(void)
{
ui_newOrExistingConnections = lv_obj_create(NULL);
lv_obj_clear_flag( ui_newOrExistingConnections, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label3 = lv_label_create(ui_newOrExistingConnections);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, -109 );
lv_obj_set_y( ui_Label3, -143 );
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"New or existing connection?");
lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x3F66E7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label3, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label4 = lv_label_create(ui_newOrExistingConnections);
lv_obj_set_width( ui_Label4, lv_pct(95));
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4, 7 );
lv_obj_set_y( ui_Label4, -83 );
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"Would you like to create a new internet connection for your device or use one you've already set up?");
lv_obj_set_style_text_align(ui_Label4, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel1 = lv_obj_create(ui_newOrExistingConnections);
lv_obj_set_width( ui_Panel1, 432);
lv_obj_set_height( ui_Panel1, 144);
lv_obj_set_x( ui_Panel1, 4 );
lv_obj_set_y( ui_Panel1, 17 );
lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_newConnectionCB = lv_checkbox_create(ui_Panel1);
lv_checkbox_set_text(ui_newConnectionCB,"create new connection");
lv_obj_set_width( ui_newConnectionCB, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_newConnectionCB, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_newConnectionCB, -3 );
lv_obj_set_y( ui_newConnectionCB, -40 );
lv_obj_set_align( ui_newConnectionCB, LV_ALIGN_LEFT_MID );
lv_obj_add_state( ui_newConnectionCB, LV_STATE_CHECKED );     /// States
lv_obj_add_flag( ui_newConnectionCB, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_text_color(ui_newConnectionCB, lv_color_hex(0x3F66E7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_newConnectionCB, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_existConnectionCB = lv_checkbox_create(ui_Panel1);
lv_checkbox_set_text(ui_existConnectionCB,"use an existing connection");
lv_obj_set_width( ui_existConnectionCB, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_existConnectionCB, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_existConnectionCB, -3 );
lv_obj_set_y( ui_existConnectionCB, 13 );
lv_obj_set_align( ui_existConnectionCB, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_existConnectionCB, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_text_color(ui_existConnectionCB, lv_color_hex(0x3F66E7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_existConnectionCB, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_NewExistingCancelBtn = lv_btn_create(ui_newOrExistingConnections);
lv_obj_set_width( ui_NewExistingCancelBtn, 100);
lv_obj_set_height( ui_NewExistingCancelBtn, 50);
lv_obj_set_x( ui_NewExistingCancelBtn, 58 );
lv_obj_set_y( ui_NewExistingCancelBtn, 123 );
lv_obj_set_align( ui_NewExistingCancelBtn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_NewExistingCancelBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_NewExistingCancelBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_NewExistingCancelBtn, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_NewExistingCancelBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_NewExistingCancelBtn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_NewExistingCancelBtn, lv_color_hex(0x3F66E7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_NewExistingCancelBtn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_NewExistingCancelBtn, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_NewExistingCancelBtn, lv_color_hex(0x3F66E7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_NewExistingCancelBtn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_NewExistingCancelBtn, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ExistingCancelL = lv_label_create(ui_NewExistingCancelBtn);
lv_obj_set_width( ui_ExistingCancelL, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ExistingCancelL, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ExistingCancelL, LV_ALIGN_CENTER );
lv_label_set_text(ui_ExistingCancelL,"CANCEL");

ui_NewExistingOkBtn = lv_btn_create(ui_newOrExistingConnections);
lv_obj_set_width( ui_NewExistingOkBtn, 100);
lv_obj_set_height( ui_NewExistingOkBtn, 50);
lv_obj_set_x( ui_NewExistingOkBtn, 169 );
lv_obj_set_y( ui_NewExistingOkBtn, 123 );
lv_obj_set_align( ui_NewExistingOkBtn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_NewExistingOkBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_NewExistingOkBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_NewExistingOkBtn, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_NewExistingOkBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_NewExistingOkBtn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_NewExistingOkBtn, lv_color_hex(0x3F66E7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_NewExistingOkBtn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_NewExistingOkBtn, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_NewExistingOkBtn, lv_color_hex(0x3F66E7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_NewExistingOkBtn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_NewExistingOkBtn, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ExistingOkL = lv_label_create(ui_NewExistingOkBtn);
lv_obj_set_width( ui_ExistingOkL, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ExistingOkL, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ExistingOkL, LV_ALIGN_CENTER );
lv_label_set_text(ui_ExistingOkL,"OK");

lv_obj_add_event_cb(ui_NewExistingOkBtn, ui_event_NewExistingOkBtn, LV_EVENT_ALL, NULL);

}
