// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_passphrase_screen_init(void)
{
ui_passphrase = lv_obj_create(NULL);
lv_obj_clear_flag( ui_passphrase, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label10 = lv_label_create(ui_passphrase);
lv_obj_set_width( ui_Label10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label10, -143 );
lv_obj_set_y( ui_Label10, -143 );
lv_obj_set_align( ui_Label10, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label10,"Enter passphrase");
lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0x3F66E7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label10, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_passphraseText = lv_textarea_create(ui_passphrase);
lv_obj_set_width( ui_passphraseText, 355);
lv_obj_set_height( ui_passphraseText, LV_SIZE_CONTENT);   /// 70
lv_obj_set_x( ui_passphraseText, -40 );
lv_obj_set_y( ui_passphraseText, -95 );
lv_obj_set_align( ui_passphraseText, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_passphraseText,"Passphrase...");



ui_Panel2 = lv_obj_create(ui_passphrase);
lv_obj_set_width( ui_Panel2, 432);
lv_obj_set_height( ui_Panel2, 141);
lv_obj_set_x( ui_Panel2, -4 );
lv_obj_set_y( ui_Panel2, 10 );
lv_obj_set_align( ui_Panel2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_Panel2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Panel2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Panel2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Panel2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Keyboard1 = lv_keyboard_create(ui_Panel2);
lv_obj_set_width( ui_Keyboard1, lv_pct(100));
lv_obj_set_height( ui_Keyboard1, lv_pct(100));
lv_obj_set_x( ui_Keyboard1, -5 );
lv_obj_set_y( ui_Keyboard1, 4 );
lv_obj_set_align( ui_Keyboard1, LV_ALIGN_CENTER );

ui_passphraseOKBtn = ui_StandardButton_create(ui_passphrase);
lv_obj_set_x( ui_passphraseOKBtn, 169 );
lv_obj_set_y( ui_passphraseOKBtn, 123 );
lv_obj_add_state( ui_passphraseOKBtn, LV_STATE_DISABLED );     /// States

ui_StandardButton1 = ui_StandardButton_create(ui_passphrase);
lv_obj_set_x( ui_StandardButton1, 58 );
lv_obj_set_y( ui_StandardButton1, 123 );

lv_label_set_text(ui_comp_get_child(ui_StandardButton1, UI_COMP_STANDARDBUTTON_LABEL12),"BACK");

lv_keyboard_set_textarea(ui_Keyboard1,ui_passphraseText);
lv_obj_add_event_cb(ui_passphraseOKBtn, ui_event_passphraseOKBtn_StandardButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_StandardButton1, ui_event_StandardButton1_StandardButton, LV_EVENT_ALL, NULL);

}
