// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_setTimeScreen_screen_init(void)
{
ui_setTimeScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_setTimeScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label7 = lv_label_create(ui_setTimeScreen);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label7, -167 );
lv_obj_set_y( ui_Label7, -143 );
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"Time/date");
lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0x3F66E7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_internetTime = lv_checkbox_create(ui_setTimeScreen);
lv_checkbox_set_text(ui_internetTime,"Set time from the Internet");
lv_obj_set_width( ui_internetTime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_internetTime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_internetTime, -76 );
lv_obj_set_y( ui_internetTime, -96 );
lv_obj_set_align( ui_internetTime, LV_ALIGN_CENTER );
lv_obj_add_state( ui_internetTime, LV_STATE_CHECKED );     /// States
lv_obj_add_flag( ui_internetTime, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_text_color(ui_internetTime, lv_color_hex(0x3F66E7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_internetTime, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TimeDateDoneBtn = ui_StandardButton_create(ui_setTimeScreen);
lv_obj_set_x( ui_TimeDateDoneBtn, 169 );
lv_obj_set_y( ui_TimeDateDoneBtn, 123 );

lv_label_set_text(ui_comp_get_child(ui_TimeDateDoneBtn, UI_COMP_STANDARDBUTTON_LABEL12),"DONE");

ui_twentyFourHrMode = lv_checkbox_create(ui_setTimeScreen);
lv_checkbox_set_text(ui_twentyFourHrMode,"24 hour mode");
lv_obj_set_width( ui_twentyFourHrMode, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_twentyFourHrMode, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_twentyFourHrMode, -122 );
lv_obj_set_y( ui_twentyFourHrMode, 52 );
lv_obj_set_align( ui_twentyFourHrMode, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_twentyFourHrMode, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_text_color(ui_twentyFourHrMode, lv_color_hex(0x3F66E7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_twentyFourHrMode, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Dropdown1 = lv_dropdown_create(ui_setTimeScreen);
lv_dropdown_set_options( ui_Dropdown1, "Greenwich Mean Time\nUniversal Coordinated Time\nEuropean Central Time +1:00\nEastern European Time +2:00\n(Arabic) Egypt Standard Time +2:00\nEastern African Time +3:00\nMiddle East Time +3:30\nNear East Time +4:00\nPakistan Lahore Time +5:00\nIndia Standard Time +5:30\nBangladesh Standard Time +6:00\nVietnam Standard Time +7:00\nChina Taiwan Time +8:00\nJapan Standard Time +9:00\nAustralia Central Time +9:30\nAustralia Eastern Time +10:00\nSolomon Standard Time +11:00\nNew Zealand Standard Time +12:00\nMidway Islands Time -11:00\nHawaii Standard Time -10:00\nAlaska Standard Time -9:00\nPacific Standard Time -8:00\nPhoenix Standard Time -7:00\nMountain Standard Time -7:00\nCentral Standard Time -6:00\nEastern Standard Time -5:00\nIndiana Eastern Standard Time -5:00\nPuerto Rico and US Virgin Islands Time -4:00\nCanada Newfoundland Time -3:30\nArgentina Standard Time -3:00\nBrazil Eastern Time -3:00\nCentral African Time -1:00" );
lv_obj_set_width( ui_Dropdown1, 342);
lv_obj_set_height( ui_Dropdown1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Dropdown1, -12 );
lv_obj_set_y( ui_Dropdown1, -30 );
lv_obj_set_align( ui_Dropdown1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_text_color(ui_Dropdown1, lv_color_hex(0x3F66E7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Dropdown1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_Dropdown1, lv_color_hex(0x3F66E7), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Dropdown1, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(lv_dropdown_get_list(ui_Dropdown1), lv_color_hex(0x3F66E7),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_Dropdown1), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label11 = lv_label_create(ui_setTimeScreen);
lv_obj_set_width( ui_Label11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label11, -128 );
lv_obj_set_y( ui_Label11, -61 );
lv_obj_set_align( ui_Label11, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label11,"Time Zone");
lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0x3F66E7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_TimeDateDoneBtn, ui_event_TimeDateDoneBtn_StandardButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_setTimeScreen, ui_event_setTimeScreen, LV_EVENT_ALL, NULL);

}
